CREATE TABLE textbookmarks (
  "TbID" INTEGER NOT NULL,
  "TbTxID" INTEGER NOT NULL,
  "TbTitle" VARCHAR(200) NOT NULL,
  PRIMARY KEY ("TbID"),
  FOREIGN KEY("TbTxID") REFERENCES "texts" ("TxID") ON UPDATE NO ACTION ON DELETE CASCADE
);
